
dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
script:
  # Tests
  - pytest --cov
after_success:
  # Upload coverage (only in Python 3.6 job, to not spam codecov with the same coverage report)
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then codecov; fi